-- MySQL Script generated by MySQL Workbench
-- Thu Nov  6 11:10:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ecommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ecommerce` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ecommerce` ;

-- -----------------------------------------------------
-- Table `ecommerce`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`categorias` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_nome_categoria` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`usuarios` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `senha` VARCHAR(255) NULL DEFAULT NULL,
  `celular` VARCHAR(255) NULL DEFAULT NULL,
  `cpf` VARCHAR(14) NULL DEFAULT NULL,
  `criado_em` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  INDEX `idx_cpf` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`enderecos` (
  `id` INT NOT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  `rua` VARCHAR(255) NULL DEFAULT NULL,
  `numero` VARCHAR(50) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NULL DEFAULT NULL,
  `cidade` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_enderecos_cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `idx_fk_endereco_usuario` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_usuario`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`),
  CONSTRAINT `fk_enderecos_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`),
  CONSTRAINT `fk_enderecos_usuario_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`pedidos` (
  `id` INT NOT NULL,
  `cliente_id` INT NULL DEFAULT NULL,
  `data_pedido` TIMESTAMP NULL DEFAULT NULL,
  `status` VARCHAR(50) NULL DEFAULT NULL,
  `total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_pedidos_cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `idx_fk_pedido_usuario` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_usuario`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`),
  CONSTRAINT `fk_pedidos_cliente_id`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `ecommerce`.`usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`produtos` (
  `id` INT NOT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `preco` DECIMAL(10,2) NULL DEFAULT NULL,
  `estoque` INT NULL DEFAULT NULL,
  `categoria_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_produtos_categoria_id` (`categoria_id` ASC) VISIBLE,
  INDEX `idx_fk_produto_categoria` (`categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_categoria`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ecommerce`.`categorias` (`id`),
  CONSTRAINT `fk_produtos_categoria_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `ecommerce`.`categorias` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ecommerce`.`itens_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ecommerce`.`itens_pedido` (
  `id` INT NOT NULL,
  `pedido_id` INT NULL DEFAULT NULL,
  `produto_id` INT NULL DEFAULT NULL,
  `quantidade` INT NULL DEFAULT NULL,
  `preco_unitario` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_itens_pedido_pedido_id` (`pedido_id` ASC) VISIBLE,
  INDEX `idx_itens_pedido_produto_id` (`produto_id` ASC) VISIBLE,
  INDEX `idx_fk_item_pedido` (`pedido_id` ASC) VISIBLE,
  INDEX `idx_fk_item_produto` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `fk_item_pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `ecommerce`.`pedidos` (`id`),
  CONSTRAINT `fk_item_produto`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ecommerce`.`produtos` (`id`),
  CONSTRAINT `fk_itens_pedido_pedido_id`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `ecommerce`.`pedidos` (`id`),
  CONSTRAINT `fk_itens_pedido_produto_id`
    FOREIGN KEY (`produto_id`)
    REFERENCES `ecommerce`.`produtos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
